version: '3'

services:
  nginx:
    hostname: nginx
    image: nginx:mainline-alpine
    volumes:
      - /var/apps/tpp/nginx.conf:/etc/nginx/nginx.conf
      - /var/apps/tpp/static:/code/static
      - /var/apps/tpp/maps:/code/maps
    links:
      - web
    ports:
      - '80:80'
      - '443:443'
    restart: always
  db:
    image: postgres
  web:
    hostname: web
    build: .
    command: gunicorn -b 0.0.0.0:29000 api.wsgi:application --reload
    volumes:
      - /var/apps/tpp:/code
    depends_on:
      - db
    links:
      - redis
    restart: always
  celery:
    hostname: celery
    build: .
    command: celery -A background_worker worker -B -l info
    volumes:
      - /var/apps/tpp:/code
    depends_on:
      - db
    links:
      - redis
    restart: always
  redis:
    image: redis:3.2-alpine
    restart: always
